# --- Servidor Socket ---
server.port=9090
server.timeout.ms=5000

# --- Concurrencia (Ajustar según cores de la LPAR) ---
pool.core.size=25
pool.max.size=150
pool.queue.capacity=1000

# --- DB2 Native Connection ---
db.url=jdbc:db2:*local
db.driver=com.ibm.db2.jdbc.app.DB2Driver
db.pool.max.size=30
db.pool.min.idle=10

# --- Seguridad ---
system.master.key=ClaveMaestraSistemaIBM